### ISSUE TITLE
Turn this into a babel-macros plugin

### ISSUE THREAD

**Issue by kentcdodds** [bernard-lin/babel-plugin-glamorous-displayname#11]
[babel-macros](https://github.com/kentcdodds/babel-macros) is a new thing that I made and I think it's pretty great. I'm going to create `glamorous.macro` and port this over to that.

**Comment by bernard-lin** [comment]
Sounds good!

**Comment by kentcdodds** [comment]
If you'd like, we can still use this repo and just rename it. I can do all the work on it and just push my stuff in a PR when I'm done :smile: However you want to do it.

**Comment by bernard-lin** [comment]
Whatever is easiest for you! 😀

**Comment by kentcdodds** [comment]
lol, I just realized that this is one situation where it wont work as a `babel-macros` macro 🙃 I guess I'm still getting used to the use cases myself!

**Comment by kentcdodds** [comment]
If you're curious, the reason why is a macro plugin must be imported to be applied:

```javascript
import glamorousMacro from 'glamorous.macro'
```

But people will be importing `glamorous` not `glamorous.macro` 😅

**Comment by bernard-lin** [comment]
Ahh makes sense. Excited to see what kind of macros people come up with though!
