### ISSUE TITLE
Plugin doesn't display name

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [bernard-lin/babel-plugin-glamorous-displayname#17]
Hello 👋 
I know this is not the best place for this, but i don't know why, this plugin doesn't work with my code 😶.

- `babel-plugin-glamorous-displayname` version:  "^2.1.0",
- `node` version: v8.7.0
- `npm` (or `yarn`) version: 1.2.1

Relevant code or config

```javascript
// .babelrc
{
  "presets": ["env", "react"],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread",
    "glamorous-displayname",
    ["module-resolver", {
      "root": ["./app"]
    }]
  ],
  "env": {
    "production": {
      "plugins": ["transform-react-remove-prop-types"]
    }
  }
}
```

What you did:
For example, this code : 
```javascript
// style.js
import { div } from 'glamorous';

export const StyledApp = div({
  color: '#fffdd8',
  display: 'flex',
  height: '100%',
  position: 'relative',
});
``` 

What happened:
In my React DevTools, i don't have `StyledApp`, just `glamorous(div)` 
<img width="494" alt="capture d ecran 2017-10-25 a 13 17 03" src="https://user-images.githubusercontent.com/24500083/31995973-ef57367c-b986-11e7-87d8-d344c1966dff.png">

Someone can help me ? 😶 
Thanks..

**Comment by kentcdodds** [comment]
Hi @AlexandreBourdeaudhui,

So your style of code is actually not supported and just works by chance. The proper and supported way to write glamorous components is like this:

```javascript
import glamorous from 'glamorous';

export const StyledApp = glamorous.div({
  color: '#fffdd8',
  display: 'flex',
  height: '100%',
  position: 'relative',
});
```

If you want to save typing you could also just do this:

```javascript
import g from 'glamorous';

export const StyledApp = g.div({
  color: '#fffdd8',
  display: 'flex',
  height: '100%',
  position: 'relative',
});
```

Good luck!
